### ISSUE TITLE
No longer seems to work with new versions

### ISSUE THREAD

**Issue by llawwehttam** [tustin2121/MCSignOnDoor#5]
This project seems to be the only one of it's kind out there so I really hope you haven't abandoned development for ever.

It no longer acts as a valid minecraft server and when you try to connect to it as a client you get nothing but error messages.

If I have some time I may submit a patch.

**Comment by lifehome** [comment]
Sorry for the bump, but is this still working with the latest 1.12.1?

**Comment by Wruczek** [comment]
Sorry for the bump, but It doesn't seem to work anymore. Anyone got an alternative?

**Comment by tustin2121** [comment]
I suggest you check the forks of this project, because I long ago stopped maintaining it. I'm surprised no one else has made something better or at least comparable since 2014, apparently. Last I did anything for Minecraft, Bukket was still a thing...
